CREATE TABLE ticket_ai_analysis (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    ticket_id BIGINT NOT NULL,
    ticket_version BIGINT NOT NULL,
    kind VARCHAR(24) NOT NULL,
    status VARCHAR(24) NOT NULL,
    source_event_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    source_event_hash CHAR(64) NULL,
    input_text MEDIUMTEXT NOT NULL,
    categories_json JSON NOT NULL,
    result_json JSON NULL,
    requested_by BIGINT NULL,
    accepted_by BIGINT NULL,
    accepted_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL,
    finished_at DATETIME(6) NULL,
    lease_owner CHAR(36) NULL,
    lease_until DATETIME(6) NULL,
    UNIQUE KEY uk_ai_snapshot (ticket_id,ticket_version,kind),
    UNIQUE KEY uk_ai_source_event (source_event_id),
    KEY idx_ai_pending (status,id),
    KEY idx_ai_lease (status,lease_until),
    FOREIGN KEY (ticket_id) REFERENCES ticket(id),
    FOREIGN KEY (requested_by) REFERENCES app_user(id),
    FOREIGN KEY (accepted_by) REFERENCES app_user(id),
    CONSTRAINT chk_ai_kind CHECK (kind IN ('CLASSIFICATION','SUMMARY','REPLY')),
    CONSTRAINT chk_ai_status CHECK (status IN ('WAITING','PENDING','PROCESSING','SUCCEEDED','FAILED','DISABLED','ACCEPTED'))
) ENGINE=InnoDB;

CREATE TABLE ai_call_log (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    analysis_id BIGINT NOT NULL,
    invocation_id CHAR(36) NOT NULL,
    model VARCHAR(200) NOT NULL,
    input_tokens INT NULL,
    output_tokens INT NULL,
    duration_ms BIGINT NOT NULL,
    attempts INT NOT NULL,
    outcome VARCHAR(24) NOT NULL,
    error_code VARCHAR(200) NULL,
    applied BOOLEAN NOT NULL,
    created_at DATETIME(6) NOT NULL,
    UNIQUE KEY uk_ai_invocation (invocation_id),
    KEY idx_ai_call_analysis (analysis_id,created_at),
    FOREIGN KEY (analysis_id) REFERENCES ticket_ai_analysis(id)
) ENGINE=InnoDB;
