import { test, expect } from '@playwright/test'
import { randomUUID } from 'node:crypto'
import { action, api, login, setup } from './fixtures'
import type { Detail, SupportGroup, TicketAssignmentRecord, TicketPage, WorkloadPage } from '../src/api/types'

test('团队真实协作：无候选保留待分配、人工分配、受限跨组转派及负载更新', async ({ page, browser }) => {
  const source = await setup(), target = await setup(), outsider = await setup()
  const agentPage = await browser.newPage()
  try {
    const { accounts, category, client, group } = source
    const targetName = `设备支持组${randomUUID().slice(0, 8)}`
    await api(client, `/api/admin/support-groups/${target.group.id}`, 'PUT', { name: targetName, leaderId: accounts.leader.id, enabled: true, version: 0 }, accounts.admin.token)
    await api(target.client, '/api/support/agents/me/online', 'PUT', { online: true, version: 0 }, target.accounts.agent.token)
    const created = await api<Detail>(client, '/api/tickets', 'POST', { title: `跨组网络问题${randomUUID().slice(0, 8)}`, description: '网络排查后需要设备组协助', categoryId: category.id, priority: 'HIGH', tags: [] }, accounts.user.token)
    const id = created.ticket.id, title = created.ticket.title
    await login(page, accounts.leader, `/team?groupId=${group.id}&queue=MANUAL`)
    await expect(page.getByRole('heading', { name: '团队工作台', exact: true })).toBeVisible()
    await expect(page.locator('.members tbody')).toContainText('离线')
    await page.getByRole('link', { name: title, exact: true }).click()
    const assignment = page.getByRole('region', { name: '工单分配与转派', exact: true })
    await assignment.getByRole('button', { name: '分配工单', exact: true }).click()
    await expect(assignment.getByText('没有符合条件的可用客服。', { exact: false })).toBeVisible()
    await expect(assignment.getByRole('button', { name: '确认分配工单', exact: true })).toBeDisabled()
    await assignment.getByRole('button', { name: '取消操作', exact: true }).click()
    await page.getByRole('link', { name: '‹ 返回团队工作台', exact: true }).click()
    await expect(page.getByRole('link', { name: title, exact: true })).toBeVisible()
    await login(agentPage, accounts.agent, '/work')
    await agentPage.getByRole('button', { name: '当前离线 · 开始接单', exact: true }).click()
    await expect(agentPage.getByText('在线接单', { exact: false })).toBeVisible()
    await page.getByRole('button', { name: '刷新工作量', exact: true }).click()
    await expect(page.locator('.members tbody')).toContainText('在线')
    await page.getByRole('link', { name: title, exact: true }).click()
    await assignment.getByRole('button', { name: '分配工单', exact: true }).click()
    await assignment.getByRole('radio').check()
    await assignment.getByLabel('分配 / 转派说明').fill('网络组先行排查')
    await assignment.getByRole('button', { name: '确认分配工单', exact: true }).click()
    await expect(assignment.getByText('分配已完成', { exact: false })).toBeVisible()
    await page.getByRole('link', { name: '‹ 返回团队工作台', exact: true }).click()
    await expect(page.getByRole('link', { name: title, exact: true })).toHaveCount(0)

    await login(agentPage, accounts.agent, `/tickets/${id}`)
    await action(agentPage, '开始处理', '网络组检查连接正常，需要设备组进一步检查')
    const agentAssignment = agentPage.getByRole('region', { name: '工单分配与转派', exact: true })
    await agentAssignment.getByRole('button', { name: '转派工单', exact: true }).click()
    await agentAssignment.getByLabel('查找客服或组').fill(targetName)
    await agentAssignment.getByRole('button', { name: '搜索 / 刷新候选', exact: true }).click()
    await expect(agentAssignment.getByText('没有符合条件的可用客服。', { exact: false })).toBeVisible()
    const denied = await client.post(`/api/tickets/${id}/transfer`, { headers: { Authorization: `Bearer ${accounts.agent.token}` }, data: { assigneeId: target.accounts.agent.id, version: 2, reason: '验证普通客服不可跨组' } })
    expect(denied.status()).toBe(403)

    await page.getByRole('button', { name: '全部工单', exact: true }).click()
    await page.getByRole('link', { name: title, exact: true }).click()
    await assignment.getByRole('button', { name: '转派工单', exact: true }).click()
    await assignment.getByLabel('查找客服或组').fill(targetName)
    await assignment.getByRole('button', { name: '搜索 / 刷新候选', exact: true }).click()
    await assignment.getByRole('radio').check()
    await expect(assignment.getByText('这是跨组转派', { exact: false })).toBeVisible()
    await assignment.getByLabel('分配 / 转派说明').fill('设备问题移交设备组处理')
    await assignment.getByRole('button', { name: '确认转派工单', exact: true }).click()
    await expect(assignment.getByText('转派已完成', { exact: false })).toBeVisible()
    await page.getByRole('link', { name: '‹ 返回团队工作台', exact: true }).click()
    await expect(page.getByRole('link', { name: title, exact: true })).toHaveCount(0)
    const sourceLoad = await api<WorkloadPage>(client, `/api/support/groups/${group.id}/workload`, 'GET', undefined, accounts.leader.token)
    expect(sourceLoad.items[0].activeCount).toBe(0)
    await page.getByLabel('客服组', { exact: true }).selectOption(String(target.group.id))
    await expect(page.getByRole('link', { name: title, exact: true })).toBeVisible()
    const targetLoad = await api<WorkloadPage>(client, `/api/support/groups/${target.group.id}/workload`, 'GET', undefined, accounts.leader.token)
    expect(targetLoad.items[0]).toMatchObject({ activeCount: 1, processingCount: 1 })
    await expect(page.locator('.members tbody tr')).toHaveCount(1)
    await expect(page.locator('.members tbody tr td').nth(1)).toHaveText('1')
    await expect(page.locator('.members tbody tr td').nth(2)).toHaveText('1')
    await page.screenshot({ path: '../docs/results/screenshots/team-workspace.png', fullPage: true })
    await page.setViewportSize({ width: 390, height: 844 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
    const mobileRefresh = page.getByRole('button', { name: '刷新团队', exact: true })
    await expect(mobileRefresh).toBeVisible()
    await Promise.all([page.waitForResponse(response => response.url().includes('/api/support/groups?') && response.request().method() === 'GET'), mobileRefresh.click()])
    await expect(page.getByRole('link', { name: title, exact: true })).toBeVisible()
    await expect(page.locator('.members tbody tr')).toHaveCount(1)
    await page.route('**/api/workspace/tickets?**', route => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ code: 'UNAVAILABLE', message: '队列暂时不可用，请稍后重试' }) }))
    await mobileRefresh.click()
    await expect(page.getByRole('alert').filter({ hasText: '队列暂时不可用' })).toBeVisible()
    await expect(page.getByRole('link', { name: title, exact: true })).toHaveCount(0)
    await expect(page.getByText('没有符合条件的工单', { exact: false })).toHaveCount(0)
    await page.unroute('**/api/workspace/tickets?**')
    await page.getByRole('button', { name: '重新加载', exact: true }).click()
    await expect(page.getByRole('link', { name: title, exact: true })).toBeVisible()
    await page.screenshot({ path: '../docs/results/screenshots/team-workspace-mobile.png', fullPage: true })
    const records = await api<TicketAssignmentRecord[]>(client, `/api/tickets/${id}/assignments`, 'GET', undefined, accounts.leader.token)
    expect(records).toHaveLength(2)
    expect(records[1]).toMatchObject({ fromGroupId: group.id, toGroupId: target.group.id, toAssigneeId: target.accounts.agent.id })
    const oldAgentAccess = await client.get(`/api/workspace/tickets/${id}`, { headers: { Authorization: `Bearer ${accounts.agent.token}` } })
    expect(oldAgentAccess.status()).toBe(403)

    await api<Detail>(client, '/api/tickets', 'POST', { title: '组长向其他组提交的问题', description: '提交身份不能扩大团队管理权限', categoryId: outsider.category.id, priority: 'HIGH', tags: [] }, accounts.leader.token)
    const managed = await api<SupportGroup[]>(client, '/api/support/groups?limit=100', 'GET', undefined, accounts.leader.token)
    expect(managed.map(item => item.id)).not.toContain(outsider.group.id)
    const foreign = await api<TicketPage>(client, `/api/workspace/tickets?view=MY_GROUP&queue=MANUAL&groupId=${outsider.group.id}`, 'GET', undefined, accounts.leader.token)
    expect(foreign.items).toHaveLength(0)
    await login(page, accounts.leader, `/team?groupId=${outsider.group.id}`)
    await expect(page.getByText('所选客服组不存在或不在你的管理范围', { exact: false })).toBeVisible()
    await expect(page.locator('.members')).toHaveCount(0)
  } finally { await agentPage.close(); await source.client.dispose(); await target.client.dispose(); await outsider.client.dispose() }
})
