import { test, expect, type Page } from '@playwright/test'
import { randomUUID } from 'node:crypto'
import { action, api, credentials, login, setup } from './fixtures'
import type { Detail, TicketHistory } from '../src/api/types'

let fixture: Awaited<ReturnType<typeof setup>>
const extraPages: Page[] = []
test.beforeAll(async () => { fixture = await setup() })
test.afterAll(async () => { await fixture?.client.dispose() })
test.afterEach(async () => { for (const page of extraPages.splice(0)) await page.close() })

test('四角色真实工单闭环：创建编辑附件、接单交流、解决关闭和重开', async ({ page, browser }) => {
  const { accounts, category, client } = fixture
  const title = `VPN无法连接${randomUUID().slice(0, 8)}`
  await login(page, accounts.user)
  await page.getByRole('link', { name: '＋ 创建工单', exact: true }).click()
  await page.getByLabel('问题标题', { exact: true }).fill(title)
  await page.getByLabel('问题描述', { exact: true }).fill('连接公司网络时提示超时，其他网站可以访问。')
  await page.getByLabel('问题分类', { exact: true }).selectOption(String(category.id))
  await page.getByLabel('优先级', { exact: true }).selectOption('HIGH')
  await page.locator('input[type=file]').setInputFiles({ name: '错误报告.pdf', mimeType: 'application/pdf', buffer: Buffer.from('%PDF-1.7\n隔离测试附件') })
  const createdResponse = page.waitForResponse(response => response.url().endsWith('/api/tickets') && response.request().method() === 'POST')
  await page.getByRole('button', { name: '提交工单', exact: true }).click()
  const created = (await (await createdResponse).json()).data as Detail
  const id = created.ticket.id
  await expect(page.getByRole('button', { name: '错误报告.pdf', exact: true })).toBeVisible()
  await expect(page.getByText('等待上传：', { exact: false })).toHaveCount(0)
  await page.getByRole('link', { name: '查看工单进展', exact: true }).click()
  await page.getByRole('button', { name: '编辑工单', exact: true }).click()
  await page.locator('.ticket-edit').getByLabel('问题标题', { exact: true }).fill(`${title}（已补充）`)
  await page.locator('.ticket-edit').getByRole('button', { name: '保存修改', exact: true }).click()
  await expect(page.getByRole('heading', { name: `${title}（已补充）`, exact: true })).toBeVisible()
  const afterEdit = await api<Detail>(client, `/api/tickets/${id}`, 'GET', undefined, accounts.admin.token)
  expect(afterEdit.ticket.responseDeadline).toBe(created.ticket.responseDeadline)
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: '删除附件 错误报告.pdf', exact: true }).click()
  await expect(page.getByRole('button', { name: '错误报告.pdf', exact: true })).toHaveCount(0)

  const agent = await browser.newPage(); extraPages.push(agent)
  await login(agent, accounts.agent, '/work')
  await agent.getByRole('button', { name: '当前离线 · 开始接单', exact: true }).click()
  await expect(agent.getByText('在线接单', { exact: false })).toBeVisible()
  const admin = await browser.newPage(); extraPages.push(admin)
  await login(admin, accounts.admin, `/tickets/${id}`)
  const assignment = admin.getByRole('region', { name: '工单分配与转派', exact: true })
  await assignment.getByRole('button', { name: '分配工单', exact: true }).click()
  await assignment.getByRole('radio').first().check()
  await assignment.getByLabel('分配 / 转派说明').fill('请网络客服排查')
  await assignment.getByRole('button', { name: '确认分配工单', exact: true }).click()
  await expect(assignment.getByText('分配已完成', { exact: false })).toBeVisible()
  await login(agent, accounts.agent, `/tickets/${id}`)
  await action(agent, '开始处理', '开始检查网络')
  await agent.locator('.composer').getByRole('checkbox').check()
  await agent.locator('.composer textarea').fill('内部排查：先检查网关配置')
  await agent.locator('.composer').getByRole('button', { name: '发送回复', exact: true }).click()
  await expect(agent.locator('.message').filter({ hasText: '内部排查：先检查网关配置' })).toBeVisible()
  await action(agent, '等待用户补充', '请补充具体报错时间')
  await login(page, accounts.user, `/tickets/${id}`)
  await expect(page.locator('.message').filter({ hasText: '内部排查：先检查网关配置' })).toHaveCount(0)
  await expect(page.locator('.detail-meta')).toContainText('待我补充')
  await page.locator('.composer textarea').fill('报错时间是今天上午9点')
  await page.locator('.composer').getByRole('button', { name: '发送回复', exact: true }).click()
  await expect(page.locator('.message').filter({ hasText: '报错时间是今天上午9点' })).toBeVisible()
  await login(agent, accounts.agent, `/tickets/${id}`)
  await action(agent, '恢复处理', '已经收到补充信息')
  await action(agent, '标记已解决', '网关配置已修复，请重新连接')
  await action(agent, '关闭工单', '确认问题已处理完毕')
  await expect(agent.locator('.detail-meta')).toContainText('已关闭')
  const leader = await browser.newPage(); extraPages.push(leader)
  await login(leader, accounts.leader, `/tickets/${id}`)
  await action(leader, '重新打开', '用户反馈相同故障再次出现')
  await expect(leader.locator('.detail-meta')).toContainText('处理中')
  await leader.locator('.history summary').click()
  await expect(leader.locator('.history')).toContainText('组长陈明')
  await leader.locator('.history').getByRole('button', { name: '分配记录', exact: true }).click()
  await expect(leader.locator('.history')).toContainText('客服小周')
  await leader.evaluate(() => window.scrollTo(0, 0))
  await leader.screenshot({ path: '../docs/results/screenshots/leader-ticket-history.png', fullPage: true })
  const history = await api<TicketHistory[]>(client, `/api/tickets/${id}/history?limit=100`, 'GET', undefined, accounts.admin.token)
  expect(history.map(record => record.toStatus)).toEqual(['CREATED', 'ASSIGNED', 'PROCESSING', 'PENDING', 'PROCESSING', 'RESOLVED', 'CLOSED', 'PROCESSING'])
})

test('两个真实浏览器会话竞争接单，仅一次成功且冲突说明保留', async ({ page, browser }) => {
  const { accounts, category, client } = fixture
  const online = await api<{ online: boolean; version: number }>(client, '/api/support/agents/me', 'GET', undefined, accounts.agent.token)
  if (!online.online) await api(client, '/api/support/agents/me/online', 'PUT', { online: true, version: online.version }, accounts.agent.token)
  const created = await api<Detail>(client, '/api/tickets', 'POST', { title: '双会话竞争接单', description: '同一个客服在两个浏览器窗口接单', categoryId: category.id, priority: 'HIGH', tags: [] }, accounts.user.token)
  const id = created.ticket.id
  await api(client, `/api/tickets/${id}/assign`, 'POST', { assigneeId: accounts.agent.id, version: 0, reason: '并发接单测试' }, accounts.admin.token)
  const second = await browser.newPage(); extraPages.push(second)
  for (const current of [page, second]) {
    await login(current, accounts.agent, `/tickets/${id}`)
    await current.getByRole('button', { name: '开始处理', exact: true }).click()
    await current.getByLabel('操作说明').fill('本窗口开始排查')
  }
  const firstResult = page.waitForResponse(response => response.url().endsWith(`/api/tickets/${id}/accept`))
  const secondResult = second.waitForResponse(response => response.url().endsWith(`/api/tickets/${id}/accept`))
  await Promise.all([page.getByRole('button', { name: '确认开始处理', exact: true }).click(), second.getByRole('button', { name: '确认开始处理', exact: true }).click()])
  const statuses = [(await firstResult).status(), (await secondResult).status()]
  expect([...statuses].sort()).toEqual([200, 409])
  const loser = statuses[0] === 409 ? page : second
  await expect(loser.getByLabel('操作说明')).toHaveValue('本窗口开始排查')
  await expect(loser.getByRole('button', { name: '确认开始处理', exact: true })).toBeDisabled()
  const history = await api<TicketHistory[]>(client, `/api/tickets/${id}/history`, 'GET', undefined, accounts.admin.token)
  expect(history.filter(record => record.toStatus === 'PROCESSING')).toHaveLength(1)
})

test('手机注册、创建和取消工单，详情保留服务时限', async ({ page }) => {
  const { category, client, accounts } = fixture
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/tickets')
  await page.getByRole('button', { name: '还没有账号？创建账号', exact: true }).click()
  await page.getByLabel('账号', { exact: true }).fill(`mobile_${randomUUID().replaceAll('-', '').slice(0, 16)}`)
  await page.getByLabel('姓名', { exact: true }).fill('手机用户')
  await page.getByLabel('密码', { exact: true }).fill(credentials.password)
  await page.getByRole('button', { name: '注册账号', exact: true }).click()
  await expect(page.getByText('注册成功，请使用刚才的密码登录。')).toBeVisible()
  await page.getByRole('button', { name: '登录', exact: true }).click()
  await page.getByRole('link', { name: '＋ 创建工单', exact: true }).click()
  await page.getByLabel('问题标题', { exact: true }).fill('手机提交的重复问题')
  await page.getByLabel('问题描述', { exact: true }).fill('从手机提交后发现已有相同工单')
  await page.getByLabel('问题分类', { exact: true }).selectOption(String(category.id))
  await page.getByLabel('优先级', { exact: true }).selectOption('HIGH')
  const result = page.waitForResponse(response => response.url().endsWith('/api/tickets') && response.request().method() === 'POST')
  await page.getByRole('button', { name: '提交工单', exact: true }).click()
  const id = ((await (await result).json()).data as Detail).ticket.id
  await page.getByRole('link', { name: '查看工单进展', exact: true }).click()
  await expect(page.getByRole('heading', { name: '服务时限', exact: true })).toBeVisible()
  await page.locator('.cancel-form summary').click()
  await page.getByLabel('取消原因').fill('已有其他工单处理')
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: '确认取消', exact: true }).click()
  await expect(page.locator('.detail-meta')).toContainText('已取消')
  await expect(page.getByText('工单已归档，不能继续回复或修改附件。')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: '../docs/results/screenshots/user-ticket-mobile.png', fullPage: true })
  await page.setViewportSize({ width: 900, height: 1000 })
  await expect(page.getByRole('heading', { name: '服务时限', exact: true })).toBeVisible()
  const ticket = await api<Detail>(client, `/api/tickets/${id}`, 'GET', undefined, accounts.admin.token)
  expect(ticket.ticket.status).toBe('CANCELLED')
})
